### ISSUE TITLE
Docker image 19.219.2 and 19.219.3 fail to run

### ISSUE THREAD

**Issue by thib3113** [renovatebot/docker-renovate#12]
**What Renovate type are you using?**

I'm using the docker image, with gitab CI each 2 hours, like this : 

```
docker pull -q renovate/renovate:${RENOVATE_VERSION} && docker run -e RENOVATE_TOKEN="$RENOVABOT_GITLAB_TOKEN" -e "RENOVATE_PLATFORM=gitlab" -e GITHUB_COM_TOKEN="$RENOVABOT_GITHUB_TOKEN" -v $PWD/renovate.js:/usr/src/app/config.js renovate/renovate:${RENOVATE_VERSION} $(cat repositories.txt)
```

**Describe the bug**

With the last run, I see the bug (19.219.3)
```
docker: Error response from daemon: OCI runtime create failed: container_linux.go:349: starting container process caused "exec: \"node\": executable file not found in $PATH": unknown.
time="2020-04-25T12:21:53+02:00" level=error msg="error waiting for container: context canceled"
```

I test with the 19.219.2, and same error .

**Did you see anything helpful in debug logs?**

no debug logs, docker image doesn't start

**To Reproduce**

Start the docker image ?

**Comment by viceice** [comment]
@thib3113 fix deployed, we need to wait for bubling to this repo. Should be happen in next few hours.

**Comment by viceice** [comment]
@thib3113 should be fixed now, can you confirm please?

**Comment by thib3113** [comment]
Yes, It's work, just now I got : 
```
 WARN: RE2 not usable, falling back to RegExp
       "err": {
         "code": "MODULE_NOT_FOUND",
         "requireStack": [
           "/usr/src/app/node_modules/renovate/dist/util/regex.js",
           "/usr/src/app/node_modules/renovate/dist/versioning/regex/index.js",
           "/usr/src/app/node_modules/renovate/dist/versioning/api.generated.js",
           "/usr/src/app/node_modules/renovate/dist/versioning/index.js",
           "/usr/src/app/node_modules/renovate/dist/config/definitions.js",
           "/usr/src/app/node_modules/renovate/dist/config/index.js",
           "/usr/src/app/node_modules/renovate/dist/workers/global/index.js",
           "/usr/src/app/node_modules/renovate/dist/renovate.js",
           "/usr/src/app/dist/renovate.js"
         ],
         "message": "Cannot find module 're2'\nRequire stack:\n- /usr/src/app/node_modules/renovate/dist/util/regex.js\n- /usr/src/app/node_modules/renovate/dist/versioning/regex/index.js\n- /usr/src/app/node_modules/renovate/dist/versioning/api.generated.js\n- /usr/src/app/node_modules/renovate/dist/versioning/index.js\n- /usr/src/app/node_modules/renovate/dist/config/definitions.js\n- /usr/src/app/node_modules/renovate/dist/config/index.js\n- /usr/src/app/node_modules/renovate/dist/workers/global/index.js\n- /usr/src/app/node_modules/renovate/dist/renovate.js\n- /usr/src/app/dist/renovate.js",
         "stack": "Error: Cannot find module 're2'\nRequire stack:\n- /usr/src/app/node_modules/renovate/dist/util/regex.js\n- /usr/src/app/node_modules/renovate/dist/versioning/regex/index.js\n- /usr/src/app/node_modules/renovate/dist/versioning/api.generated.js\n- /usr/src/app/node_modules/renovate/dist/versioning/index.js\n- /usr/src/app/node_modules/renovate/dist/config/definitions.js\n- /usr/src/app/node_modules/renovate/dist/config/index.js\n- /usr/src/app/node_modules/renovate/dist/workers/global/index.js\n- /usr/src/app/node_modules/renovate/dist/renovate.js\n- /usr/src/app/dist/renovate.js\n    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:980:15)\n    at Function.Module._load (internal/modules/cjs/loader.js:862:27)\n    at Module.require (internal/modules/cjs/loader.js:1042:19)\n    at require (internal/modules/cjs/helpers.js:77:18)\n    at Object.<anonymous> (/usr/src/app/node_modules/renovate/dist/util/regex.js:8:17)\n    at Module._compile (internal/modules/cjs/loader.js:1156:30)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)\n    at Module.load (internal/modules/cjs/loader.js:1000:32)\n    at Function.Module._load (internal/modules/cjs/loader.js:899:14)\n    at Module.require (internal/modules/cjs/loader.js:1042:19)\n    at require (internal/modules/cjs/helpers.js:77:18)\n    at Object.<anonymous> (/usr/src/app/node_modules/renovate/dist/versioning/regex/index.js:5:17)\n    at Module._compile (internal/modules/cjs/loader.js:1156:30)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)\n    at Module.load (internal/modules/cjs/loader.js:1000:32)\n    at Function.Module._load (internal/modules/cjs/loader.js:899:14)\n    at Module.require (internal/modules/cjs/loader.js:1042:19)\n    at require (internal/modules/cjs/helpers.js:77:18)\n    at Object.<anonymous> (/usr/src/app/node_modules/renovate/dist/versioning/api.generated.js:25:28)\n    at Module._compile (internal/modules/cjs/loader.js:1156:30)"
       }
```

**Comment by rarkins** [comment]
@viceice 

```
2020-04-25T20:55:52.3883453Z #40 34.24 warning Error running install script for optional dependency: "/usr/src/app/node_modules/re2: Command failed.
2020-04-25T20:55:52.3883737Z #40 34.24 Exit code: 1
2020-04-25T20:55:52.3884150Z #40 34.24 Command: node-gyp rebuild
2020-04-25T20:55:52.3884400Z #40 34.24 Arguments: 
2020-04-25T20:55:52.3885072Z #40 34.24 Directory: /usr/src/app/node_modules/re2
2020-04-25T20:55:52.3885340Z #40 34.24 Output:
2020-04-25T20:55:52.3885573Z #40 34.24 gyp info it worked if it ends with ok
2020-04-25T20:55:52.3885998Z #40 34.24 gyp info using node-gyp@6.1.0
2020-04-25T20:55:52.3886250Z #40 34.24 gyp info using node@12.16.2 | linux | x64
2020-04-25T20:55:52.3886504Z #40 34.24 gyp info find Python using Python version 3.6.9 found at \"/usr/bin/python3\"
2020-04-25T20:55:52.3887077Z #40 34.24 gyp http GET https://nodejs.org/download/release/v12.16.2/node-v12.16.2-headers.tar.gz
2020-04-25T20:55:52.3887614Z #40 34.24 gyp http 200 https://nodejs.org/download/release/v12.16.2/node-v12.16.2-headers.tar.gz
2020-04-25T20:55:52.3887932Z #40 34.24 gyp http GET https://nodejs.org/download/release/v12.16.2/SHASUMS256.txt
2020-04-25T20:55:52.3888484Z #40 34.24 gyp http 200 https://nodejs.org/download/release/v12.16.2/SHASUMS256.txt
2020-04-25T20:55:52.3888769Z #40 34.24 gyp info spawn /usr/bin/python3
2020-04-25T20:55:52.3889009Z #40 34.24 gyp info spawn args [
2020-04-25T20:55:52.3889528Z #40 34.24 gyp info spawn args   '/usr/local/node-v12.16.2-linux-x64/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
2020-04-25T20:55:52.3889967Z #40 34.24 gyp info spawn args   'binding.gyp',
2020-04-25T20:55:52.3890372Z #40 34.24 gyp info spawn args   '-f',
2020-04-25T20:55:52.3890774Z #40 34.24 gyp info spawn args   'make',
2020-04-25T20:55:52.3891171Z #40 34.24 gyp info spawn args   '-I',
2020-04-25T20:55:52.3891790Z #40 34.24 gyp info spawn args   '/usr/src/app/node_modules/re2/build/config.gypi',
2020-04-25T20:55:52.3892206Z #40 34.24 gyp info spawn args   '-I',
2020-04-25T20:55:52.3892709Z #40 34.24 gyp info spawn args   '/usr/local/node-v12.16.2-linux-x64/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
2020-04-25T20:55:52.3893140Z #40 34.24 gyp info spawn args   '-I',
2020-04-25T20:55:52.3893619Z #40 34.24 gyp info spawn args   '/root/.cache/node-gyp/12.16.2/include/node/common.gypi',
2020-04-25T20:55:52.3894072Z #40 34.24 gyp info spawn args   '-Dlibrary=shared_library',
2020-04-25T20:55:52.3894530Z #40 34.24 gyp info spawn args   '-Dvisibility=default',
2020-04-25T20:55:52.3894985Z #40 34.24 gyp info spawn args   '-Dnode_root_dir=/root/.cache/node-gyp/12.16.2',
2020-04-25T20:55:52.3896030Z #40 34.24 gyp info spawn args   '-Dnode_gyp_dir=/usr/local/node-v12.16.2-linux-x64/lib/node_modules/npm/node_modules/node-gyp',
2020-04-25T20:55:52.3897089Z #40 34.24 gyp info spawn args   '-Dnode_lib_file=/root/.cache/node-gyp/12.16.2/<(target_arch)/node.lib',
2020-04-25T20:55:52.3897587Z #40 34.24 gyp info spawn args   '-Dmodule_root_dir=/usr/src/app/node_modules/re2',
2020-04-25T20:55:52.3898023Z #40 34.24 gyp info spawn args   '-Dnode_engine=v8',
2020-04-25T20:55:52.3898439Z #40 34.24 gyp info spawn args   '--depth=.',
2020-04-25T20:55:52.3898863Z #40 34.24 gyp info spawn args   '--no-parallel',
2020-04-25T20:55:52.3899295Z #40 34.24 gyp info spawn args   '--generator-output',
2020-04-25T20:55:52.3899705Z #40 34.24 gyp info spawn args   'build',
2020-04-25T20:55:52.3900119Z #40 34.24 gyp info spawn args   '-Goutput_dir=.'
2020-04-25T20:55:52.3900366Z #40 34.24 gyp info spawn args ]
2020-04-25T20:55:52.3900604Z #40 34.24 Traceback (most recent call last):
2020-04-25T20:55:52.3901120Z #40 34.24   File \"/usr/local/node-v12.16.2-linux-x64/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py\", line 47, in <module>
2020-04-25T20:55:52.3901394Z #40 34.24     import gyp
2020-04-25T20:55:52.3901924Z #40 34.24   File \"/usr/local/node-v12.16.2-linux-x64/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py\", line 10, in <module>
2020-04-25T20:55:52.3902197Z #40 34.24     import gyp.input
2020-04-25T20:55:52.3902715Z #40 34.24   File \"/usr/local/node-v12.16.2-linux-x64/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/input.py\", line 9, in <module>
2020-04-25T20:55:52.3902992Z #40 34.24     import gyp.common
2020-04-25T20:55:52.3903505Z #40 34.24   File \"/usr/local/node-v12.16.2-linux-x64/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/common.py\", line 6, in <module>
2020-04-25T20:55:52.3903775Z #40 34.24     import filecmp
2020-04-25T20:55:52.3904442Z #40 34.24 ModuleNotFoundError: No module named 'filecmp'
2020-04-25T20:55:52.3904848Z #40 34.24 gyp ERR! configure error 
2020-04-25T20:55:52.3905163Z #40 34.24 gyp ERR! stack Error: `gyp` failed with exit code: 1
2020-04-25T20:55:52.3905781Z #40 34.24 gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/node-v12.16.2-linux-x64/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)
2020-04-25T20:55:52.3906072Z #40 34.24 gyp ERR! stack     at ChildProcess.emit (events.js:310:20)
2020-04-25T20:55:52.3906339Z #40 34.24 gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
2020-04-25T20:55:52.3906787Z #40 34.24 gyp ERR! System Linux 5.0.0-1035-azure
2020-04-25T20:55:52.3907498Z #40 34.24 gyp ERR! command \"/usr/local/node-v12.16.2-linux-x64/bin/node\" \"/usr/local/node-v12.16.2-linux-x64/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js\" \"rebuild\"
2020-04-25T20:55:52.3907829Z #40 34.24 gyp ERR! cwd /usr/src/app/node_modules/re2
2020-04-25T20:55:52.3908313Z #40 34.24 gyp ERR! node -v v12.16.2
2020-04-25T20:55:52.3908997Z #40 34.24 gyp ERR! node-gyp -v v6.1.0
2020-04-25T20:55:52.3909304Z #40 34.24 gyp ERR! not ok"
2020-04-25T20:55:52.3909551Z #40 34.24 info This module is OPTIONAL, you can safely ignore this error
```

**Comment by viceice** [comment]
This new errror is the same as #13, so i close this in favor
