### ISSUE TITLE
Install python and pip behind corporate proxy

### ISSUE THREAD

**Issue by y0x** [renovatebot/docker-renovate#1680]
Currently trying to build our own docker image based on renovate slim and using this in AWS ECR. Before we used the full image where python and pip was already installed, but due to too many security vulnerablities in that image we are now forced to go with the slim version and only install what we actually need to minimise the findings.

Our entire network traffic goes through a ssl inspector, which means I have to always provide a specific ssl certificate in order to reach the internet.

```
FROM renovate/renovate:latest

USER 0
COPY cert.pem /usr/local/share/ca-certificates/my-root-ca.crt
RUN update-ca-certificates

# configure node
ENV NODE_EXTRA_CA_CERTS=/usr/local/share/ca-certificates/my-root-ca.crt

RUN curl https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip -o "awscliv2.zip" && \
    unzip awscliv2.zip && \
    ./aws/install && \
    rm -rf awscliv2.zip ./aws

# renovate: datasource=github-releases lookupName=containerbase/python-prebuild
RUN install-tool python 3.11.4
```

In general this works, but I got a bit confused that when trying to run `RUN install-tool python 3.11.4` it actually seems to use pip to install this or I got this wrong. But I see this message when trying to build the image:

```
 > [5/8] RUN install-tool python 3.11.4:
#9 0.496 [12:52:37.456] INFO (1): Installing tool python v3.11.4...
#9 0.508 installing v2 tool python v3.11.4
#9 12.99 WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1002)'))': /simple/pip/
#9 13.63 WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1002)'))': /simple/pip/
#9 14.78 WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1002)'))': /simple/pip/
#9 16.94 WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1002)'))': /simple/pip/
#9 21.09 WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1002)'))': /simple/pip/
#9 21.44 WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1002)'))': /simple/virtualenv/
#9 22.09 WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1002)'))': /simple/virtualenv/
#9 23.23 WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1002)'))': /simple/virtualenv/
#9 25.44 WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1002)'))': /simple/virtualenv/
#9 29.60 WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1002)'))': /simple/virtualenv/
#9 29.75 ERROR: Could not find a version that satisfies the requirement virtualenv (from versions: none)
#9 29.75 ERROR: No matching distribution found for virtualenv
#9 29.83 [12:53:06.791] FATAL (1): Command failed with exit code 1: /usr/local/containerbase/bin/install-tool python 3.11.4
#9 29.83     err: {
#9 29.83       "type": "Error",
#9 29.83       "message": "Command failed with exit code 1: /usr/local/containerbase/bin/install-tool python 3.11.4",
#9 29.83       "stack":
#9 29.83           Error: Command failed with exit code 1: /usr/local/containerbase/bin/install-tool python 3.11.4
#9 29.83               at makeError (/snapshot/dist/containerbase-cli.js:40984:13)
#9 29.83               at handlePromise (/snapshot/dist/containerbase-cli.js:41440:29)
#9 29.83               at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
#9 29.83               at async InstallLegacyToolService.execute (/snapshot/dist/containerbase-cli.js:42312:5)
#9 29.83               at async InstallToolService.execute (/snapshot/dist/containerbase-cli.js:42478:7)
#9 29.83               at async InstallToolShortCommand.execute (/snapshot/dist/containerbase-cli.js:42547:14)
#9 29.83               at async InstallToolShortCommand.validateAndExecute (/snapshot/dist/containerbase-cli.js:1342:26)
#9 29.83               at async _Cli.run (/snapshot/dist/containerbase-cli.js:2455:22)
#9 29.83               at async _Cli.runExit (/snapshot/dist/containerbase-cli.js:2463:28)
#9 29.83               at async main (/snapshot/dist/containerbase-cli.js:42707:3)
#9 29.83       "shortMessage": "Command failed with exit code 1: /usr/local/containerbase/bin/install-tool python 3.11.4",
#9 29.83       "command": "/usr/local/containerbase/bin/install-tool python 3.11.4",
#9 29.83       "escapedCommand": "\"/usr/local/containerbase/bin/install-tool\" python 3.11.4",
#9 29.83       "exitCode": 1,
#9 29.83       "cwd": "/usr/src/app",
#9 29.83       "failed": true,
#9 29.83       "timedOut": false,
#9 29.83       "isCanceled": false,
#9 29.83       "killed": false
#9 29.83     }
```

Is there a way to use the install-tool toolset for my purpose or do I have to install python & pip via curl for example?

**Comment by viceice** [comment]
so pip is failing. shouldn't python and pip use the system certificates? 🤔

**Comment by viceice** [comment]
https://github.com/containerbase/base/blob/ce376824eeac2db23a17e27b91928bd1e92af55f/test/latest/Dockerfile#L82

**Comment by y0x** [comment]
Hm, I tried a few things now... do you have an idea whats else I could try?
```

ENV SSL_CERT_FILE=/usr/local/share/ca-certificates/my-root-ca.crt
ENV REQUESTS_CA_BUNDLE=/usr/local/share/ca-certificates/my-root-ca.crt
ENV CURL_CA_BUNDLE=/usr/local/share/ca-certificates/my-root-ca.crt

COPY cert.pem /test/ca.pem

RUN install-tool python 3.11.4

```

**Comment by viceice** [comment]
Please test this:

```dockerfile
FROM renovate/renovate

USER 0
COPY cert.pem /usr/local/share/ca-certificates/my-root-ca.crt
RUN update-ca-certificates

# configure node
ENV NODE_EXTRA_CA_CERTS=/usr/local/share/ca-certificates/my-root-ca.crt

ARG CONTAINERBASE_DEBUG=true

# renovate: datasource=github-releases lookupName=containerbase/python-prebuild
RUN install-tool python 3.11.4
```

this should give a lot more output, please post it here
