### ISSUE TITLE
Error when trying out sample Bitbucket pipeline: Could not parse config file  

### ISSUE THREAD

**Issue by alvindizon** [renovatebot/docker-renovate#633]
I tried setting up Renovatebot for my Bitbucket repo using this: https://github.com/renovatebot/docker-renovate/blob/main/docs/bitbucket.md, so I've set up a repo accordingly, with USERNAME and PASSWORD of a Bitbucket account set up as repo variables.

And I got the following error in the renovate step when running the pipeline:
```
DEBUG: Using RE2 as regex engine
DEBUG: Parsing configs
DEBUG: Checking for config file in /opt/atlassian/pipelines/agent/build/config.js
FATAL: Could not parse config file 
        /opt/atlassian/pipelines/agent/build/config.js:5
         password: process.env.PASSWORD
         ^^^^^^^^
       
       SyntaxError: Unexpected identifier
           at compileFunction (<anonymous>)
           at Object.compileFunction (node:vm:360:18)
           at wrapSafe (node:internal/modules/cjs/loader:1055:15)
           at Module._compile (node:internal/modules/cjs/loader:1090:27)
           at Object.Module._extensions..js (node:internal/modules/cjs/loader:1180:10)
           at Module.load (node:internal/modules/cjs/loader:1004:32)
           at Function.Module._load (node:internal/modules/cjs/loader:839:12)
           at Module.require (node:internal/modules/cjs/loader:1028:19)
           at require (node:internal/modules/cjs/helpers:102:18)
           at /usr/src/app/node_modules/renovate/lib/workers/global/config/parse/file.ts:22:25
           at getParsedContent (/usr/src/app/node_modules/renovate/lib/workers/global/config/parse/file.ts:22:25)
           at Object.getConfig (/usr/src/app/node_modules/renovate/lib/workers/global/config/parse/file.ts:52:14)
           at parseConfigs (/usr/src/app/node_modules/renovate/lib/workers/global/config/parse/index.ts:21:22)
           at Object.start (/usr/src/app/node_modules/renovate/lib/workers/global/index.ts:111:14)
           at /usr/src/app/node_modules/renovate/lib/renovate.ts:16:22
```

Any idea what this is about?

**Comment by alvindizon** [comment]
Closing this, it was just a typo.
